# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: positions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpositions.proto\"4\n\x0fPositionRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\tdirection\x18\x02 \x01(\t\"0\n\x10PositionResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x02\x32M\n\x0fPositionService\x12:\n\x11GetPositionStream\x12\x10.PositionRequest\x1a\x11.PositionResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'positions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITIONREQUEST._serialized_start=19
  _POSITIONREQUEST._serialized_end=71
  _POSITIONRESPONSE._serialized_start=73
  _POSITIONRESPONSE._serialized_end=121
  _POSITIONSERVICE._serialized_start=123
  _POSITIONSERVICE._serialized_end=200
# @@protoc_insertion_point(module_scope)
