# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import positions_pb2 as positions__pb2


class PositionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositionStream = channel.unary_stream(
                '/PositionService/GetPositionStream',
                request_serializer=positions__pb2.PositionRequest.SerializeToString,
                response_deserializer=positions__pb2.PositionResponse.FromString,
                )


class PositionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPositionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PositionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPositionStream,
                    request_deserializer=positions__pb2.PositionRequest.FromString,
                    response_serializer=positions__pb2.PositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PositionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PositionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPositionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PositionService/GetPositionStream',
            positions__pb2.PositionRequest.SerializeToString,
            positions__pb2.PositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
